# Generated by Django 5.1.6 on 2025-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='uploads/product/'),
        ),
    ]
